### ISSUE TITLE
memcpy 引起的core

### ISSUE THREAD

**Issue by zzwangforza** [LeechanX/RingLog#1]
你好：
     append这个函数，memcpy(_data + _used_len, log_line, len);这句话很偶现会引起程序core

**Comment by LeechanX** [comment]
求场景，我看一下

**Comment by xiaqing0403** [comment]
这个解决了吗，我也碰到了

**Comment by LeechanX** [comment]
可以提供一下你的使用方法以及当时的gdb core信息吗？
