### ISSUE TITLE
日志生成格式

### ISSUE THREAD

**Issue by littlel** [LeechanX/RingLog#2]
请问日志打印的格式可以自由调整吗？还有是按照天生成日志文件的吗？会自动清理日志吗？谢谢~

**Comment by LeechanX** [comment]
1、从rlog.h的251行开始就是格式，您可以修改成您想要的；

2、是按照天生成日志，且一天中的日志按照1GB（LOG_USE_LIMIT）进行滚动，最新日志是.log，接下来是.log.1，.log.2，.log.3 都是1GB；

3、不含自动删除，因为你有可能要用到前一天的日志去定位程序问题，所以这里开放。

________________________________
发件人: littlel <notifications@github.com>
发送时间: 2018年2月6日 16:08:44
收件人: LeechanX/Ring-Log
抄送: Subscribed
主题: [LeechanX/Ring-Log] 日志生成格式 (#2)


请问日志打印的格式可以自由调整吗？还有是按照天生成日志文件的吗？会自动清理日志吗？谢谢~

―

**Comment by xiaoluoluo** [comment]
请问一下  如果一次写入的日志比较大    cell_buffer  装不下  怎么办，   日志的大小 不确定  这种情况呢？ 例如 一会1兆  一会100 兆
